name: ci-prod
on:
  push:
    branches:
      - main
jobs:
  build-apk:
    name: build-apk 
    runs-on: ubuntu-latest
    steps:
      - name:  Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name:  Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-cache: true
          expo-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build apk
        run: eas build --platform android --non-interactive --profile development
  build-aab:
    name: build-aab
    runs-on: ubuntu-latest
    needs: build-apk
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: eas build --non-interactive
      
