name: ci
on: pull_request

jobs:
  perview:
    name: perview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret"
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto
  build:
    name: build 
    runs-on: ubuntu-latest
    steps:
      - name:  Setup repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name:  Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-cache: true
          expo-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build apk
        run: |
              EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
              echo "action_state<<$EOF" >> "$GITHUB_ENV" 
              eas build --platform android --non-interactive --profile development >> "$GITHUB_ENV"
              echo "$EOF" >> "$GITHUB_ENV"
      - name: Create comment
        run: gh pr comment ${{ github.event.pull_request.number }} --body "App is cooked pls take a look \n \`\`\`\n ${{ env.action_state }}\`\`\`"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
